# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renamer_ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 628)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 501, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout.addWidget(self.pushButton_browse)
        self.listWidget_selected = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget_selected.setGeometry(QtCore.QRect(30, 110, 191, 441))
        self.listWidget_selected.setObjectName("listWidget_selected")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(260, 90, 491, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_prefix = QtWidgets.QWidget()
        self.tab_prefix.setObjectName("tab_prefix")
        self.lineEdit_user_prefix = QtWidgets.QLineEdit(self.tab_prefix)
        self.lineEdit_user_prefix.setGeometry(QtCore.QRect(10, 60, 151, 20))
        self.lineEdit_user_prefix.setObjectName("lineEdit_user_prefix")
        self.label_2 = QtWidgets.QLabel(self.tab_prefix)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_prefix)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 181, 16))
        self.label_3.setObjectName("label_3")
        self.listWidget_results = QtWidgets.QListWidget(self.tab_prefix)
        self.listWidget_results.setGeometry(QtCore.QRect(20, 130, 231, 271))
        self.listWidget_results.setObjectName("listWidget_results")
        self.pushButton_update = QtWidgets.QPushButton(self.tab_prefix)
        self.pushButton_update.setGeometry(QtCore.QRect(210, 60, 75, 23))
        self.pushButton_update.setObjectName("pushButton_update")
        self.tabWidget.addTab(self.tab_prefix, "")
        self.tab_suffix = QtWidgets.QWidget()
        self.tab_suffix.setObjectName("tab_suffix")
        self.tabWidget.addTab(self.tab_suffix, "")
        self.pushButton_up = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_up.setGeometry(QtCore.QRect(220, 110, 41, 21))
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_down.setGeometry(QtCore.QRect(220, 140, 41, 21))
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_del = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_del.setGeometry(QtCore.QRect(220, 170, 41, 21))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_sort = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_sort.setGeometry(QtCore.QRect(220, 200, 41, 21))
        self.pushButton_sort.setObjectName("pushButton_sort")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 768, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose folder with files that will be renamed:"))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse..."))
        self.label_2.setText(_translate("MainWindow", "Prefix:"))
        self.label_3.setText(_translate("MainWindow", "use $ as placeholder for sequence"))
        self.pushButton_update.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_prefix), _translate("MainWindow", "Add prefix"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_suffix), _translate("MainWindow", "Add suffix"))
        self.pushButton_up.setText(_translate("MainWindow", "^"))
        self.pushButton_down.setText(_translate("MainWindow", "v"))
        self.pushButton_del.setText(_translate("MainWindow", "X"))
        self.pushButton_sort.setText(_translate("MainWindow", "A-Z"))


